// Package ply provides functionality to write PLY (Polygon File Format) files.
// PLY is a common format for storing 3D point cloud data with vertex colors.
package ply

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"io"
)

// Point represents a 3D point with color information.
type Point struct {
	X, Y, Z float32 // 3D coordinates
	R, G, B uint8   // RGB color values (0-255)
}

// Writer writes point cloud data to PLY format.
type Writer struct {
	format Format
}

// Format specifies the PLY file format.
type Format int

const (
	// FormatBinaryLittleEndian produces binary PLY with little-endian byte order.
	// This is the most compact and fastest to parse format.
	FormatBinaryLittleEndian Format = iota

	// FormatASCII produces human-readable ASCII PLY.
	// Larger file size but useful for debugging.
	FormatASCII
)

// NewWriter creates a new PLY writer with the specified format.
func NewWriter(format Format) *Writer {
	return &Writer{format: format}
}

// NewBinaryWriter creates a writer for binary little-endian PLY format.
func NewBinaryWriter() *Writer {
	return NewWriter(FormatBinaryLittleEndian)
}

// Write writes the point cloud to the given writer.
func (w *Writer) Write(out io.Writer, points []Point) error {
	// Write header
	if err := w.writeHeader(out, len(points)); err != nil {
		return fmt.Errorf("failed to write header: %w", err)
	}

	// Write vertex data
	switch w.format {
	case FormatBinaryLittleEndian:
		return w.writeBinaryData(out, points)
	case FormatASCII:
		return w.writeASCIIData(out, points)
	default:
		return fmt.Errorf("unsupported format: %d", w.format)
	}
}

// WriteToBytes writes the point cloud and returns the PLY data as bytes.
func (w *Writer) WriteToBytes(points []Point) ([]byte, error) {
	var buf bytes.Buffer
	if err := w.Write(&buf, points); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// writeHeader writes the PLY header.
func (w *Writer) writeHeader(out io.Writer, numVertices int) error {
	formatStr := "binary_little_endian"
	if w.format == FormatASCII {
		formatStr = "ascii"
	}

	header := fmt.Sprintf(`ply
format %s 1.0
comment Generated by Iris3D
element vertex %d
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
end_header
`, formatStr, numVertices)

	_, err := out.Write([]byte(header))
	return err
}

// writeBinaryData writes vertex data in binary format.
func (w *Writer) writeBinaryData(out io.Writer, points []Point) error {
	for i := range points {
		p := &points[i]

		// Write XYZ as float32 (little-endian)
		if err := binary.Write(out, binary.LittleEndian, p.X); err != nil {
			return err
		}
		if err := binary.Write(out, binary.LittleEndian, p.Y); err != nil {
			return err
		}
		if err := binary.Write(out, binary.LittleEndian, p.Z); err != nil {
			return err
		}

		// Write RGB as uint8
		if _, err := out.Write([]byte{p.R, p.G, p.B}); err != nil {
			return err
		}
	}
	return nil
}

// writeASCIIData writes vertex data in ASCII format.
func (w *Writer) writeASCIIData(out io.Writer, points []Point) error {
	for i := range points {
		p := &points[i]
		line := fmt.Sprintf("%f %f %f %d %d %d\n", p.X, p.Y, p.Z, p.R, p.G, p.B)
		if _, err := out.Write([]byte(line)); err != nil {
			return err
		}
	}
	return nil
}

// PointsFromRaw converts raw point cloud data (Nx6 float32 array) to Point slice.
// The input format is [X, Y, Z, R, G, B] for each point, where R, G, B are 0-255.
func PointsFromRaw(data []byte, numPoints int) ([]Point, error) {
	expectedSize := numPoints * 6 * 4 // 6 float32 values per point
	if len(data) != expectedSize {
		return nil, fmt.Errorf(
			"data size mismatch: expected %d bytes, got %d",
			expectedSize, len(data),
		)
	}

	points := make([]Point, numPoints)
	reader := bytes.NewReader(data)

	for i := 0; i < numPoints; i++ {
		var x, y, z, r, g, b float32

		if err := binary.Read(reader, binary.LittleEndian, &x); err != nil {
			return nil, err
		}
		if err := binary.Read(reader, binary.LittleEndian, &y); err != nil {
			return nil, err
		}
		if err := binary.Read(reader, binary.LittleEndian, &z); err != nil {
			return nil, err
		}
		if err := binary.Read(reader, binary.LittleEndian, &r); err != nil {
			return nil, err
		}
		if err := binary.Read(reader, binary.LittleEndian, &g); err != nil {
			return nil, err
		}
		if err := binary.Read(reader, binary.LittleEndian, &b); err != nil {
			return nil, err
		}

		points[i] = Point{
			X: x, Y: y, Z: z,
			R: uint8(clamp(r, 0, 255)),
			G: uint8(clamp(g, 0, 255)),
			B: uint8(clamp(b, 0, 255)),
		}
	}

	return points, nil
}

// clamp restricts a value to the given range.
func clamp(v, min, max float32) float32 {
	if v < min {
		return min
	}
	if v > max {
		return max
	}
	return v
}
